/************************************************* ***********************
* Palabra de honor:
* - No he discutido ni mostrado el código de mi programa con alguien que no sea mi
*compañero, Profesor o con el monitor asignado a este curso.
*
* - No he utilizado código obtenido de otro u otros estudiantes,
* O cualquier otra fuente no autorizada, ya sea modificado o sin modificar.
*
* - Si cualquier código o documentación utilizada en mi programa
* Fue obtenido de otra fuente, tal como un libro de texto o curso
* Notas, debe ser claramente señalado con una cita apropiada en
* Los comentarios de mi programa.
*
* <sebastian hernandez perez – 0221710005>
*
************************************************** ********************* /
* /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 *//*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import parquenatural.*;

/**
 *
 * @author law
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    
    Image icon = new ImageIcon(getClass().getResource("/vista/imagenes/logo.png")).getImage();
    private ArrayList<Region> regiones = new ArrayList<Region>();
    private ArrayList<Especie> nuevas_especies = new ArrayList<Especie>();
    private ArrayList<Area> nuevas_areas = new ArrayList<Area>();
    private ArrayList<Alojamiento> nuevos_alojamientos = new ArrayList<Alojamiento>();
    
    private ArrayList<Parque> PARQUES = new ArrayList<Parque>();
    
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        llenarDatos();
        initComponents();
        setTitle("Gestión de Parques Naturales");
        setIconImage(icon);
        setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lab_titulo = new javax.swing.JLabel();
        panelDePestanias = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        panelNuevoParque = new javax.swing.JPanel();
        lab_descripcion_aniadirparque = new javax.swing.JLabel();
        lab_nuevo_nombre = new javax.swing.JLabel();
        lab_nuevo_fecha = new javax.swing.JLabel();
        lab_nuevo_entradas = new javax.swing.JLabel();
        lab_nuevo_ubicacion = new javax.swing.JLabel();
        panelAreas = new javax.swing.JPanel();
        lab_nueva_area_nombre = new javax.swing.JLabel();
        lab_nueva_area_km = new javax.swing.JLabel();
        campo_nuevo_parque_area_nombre = new javax.swing.JTextField();
        campo_nuevo_parque_area_km = new javax.swing.JTextField();
        bot_nueva_especie_animal = new javax.swing.JButton();
        bot_nueva_especie_vegetal = new javax.swing.JButton();
        panelEspeciesExistentes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area_especies_existentes = new javax.swing.JTextArea();
        bot_guardarArea = new javax.swing.JButton();
        bot_limpiarCampos_area_area = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        campo_alojamientos = new javax.swing.JTextField();
        campo_nuevo_parque_nopmbre = new javax.swing.JTextField();
        campo_nuevo_parque_fecha = new javax.swing.JTextField();
        campo_nuevo_parque_entradas = new javax.swing.JTextField();
        combo_ubicacion_1 = new javax.swing.JComboBox<>();
        combo_ubicacion_2 = new javax.swing.JComboBox<>();
        combo_ubicacion_3 = new javax.swing.JComboBox<>();
        combo_ubicacion_4 = new javax.swing.JComboBox<>();
        panelAreasExistentes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_areas_existentes = new javax.swing.JTextArea();
        bot_limpiar_campos_areas = new javax.swing.JButton();
        bot_GuardarParque = new javax.swing.JButton();
        panelGestionarParque = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaDeParques = new javax.swing.JTable();
        panelVisitas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 0));

        panelPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lab_titulo.setBackground(new java.awt.Color(0, 255, 0));
        lab_titulo.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        lab_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/titulo.png"))); // NOI18N

        panelDePestanias.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N

        panelNuevoParque.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 0)));

        lab_descripcion_aniadirparque.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        lab_descripcion_aniadirparque.setText("Descripcion de la ventana aqui Descripcion de la ventana aqui Descripcion de la ventana aqui Descripcion de la ventana aqui Descripcion de la ventana aqui Descripcion de la ventana aqui");

        lab_nuevo_nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab_nuevo_nombre.setText("Nombre:");

        lab_nuevo_fecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab_nuevo_fecha.setText("Fecha de inaguración");

        lab_nuevo_entradas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab_nuevo_entradas.setText("Numero de entradas:");

        lab_nuevo_ubicacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab_nuevo_ubicacion.setText("Ubicacion:");

        panelAreas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Áreas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        lab_nueva_area_nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab_nueva_area_nombre.setText("Nombre:");

        lab_nueva_area_km.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab_nueva_area_km.setText("Kilometros cuadrados:");

        campo_nuevo_parque_area_nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campo_nuevo_parque_area_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campo_nuevo_parque_area_km.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campo_nuevo_parque_area_km.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        bot_nueva_especie_animal.setText("Añadir especie animal");
        bot_nueva_especie_animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_nueva_especie_animalActionPerformed(evt);
            }
        });

        bot_nueva_especie_vegetal.setText("Añadir especie vegetal");
        bot_nueva_especie_vegetal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_nueva_especie_vegetalActionPerformed(evt);
            }
        });

        panelEspeciesExistentes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Especies existentes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        area_especies_existentes.setEditable(false);
        area_especies_existentes.setColumns(20);
        area_especies_existentes.setRows(5);
        jScrollPane2.setViewportView(area_especies_existentes);

        javax.swing.GroupLayout panelEspeciesExistentesLayout = new javax.swing.GroupLayout(panelEspeciesExistentes);
        panelEspeciesExistentes.setLayout(panelEspeciesExistentesLayout);
        panelEspeciesExistentesLayout.setHorizontalGroup(
            panelEspeciesExistentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelEspeciesExistentesLayout.setVerticalGroup(
            panelEspeciesExistentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        bot_guardarArea.setText("Guardar área");
        bot_guardarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_guardarAreaActionPerformed(evt);
            }
        });

        bot_limpiarCampos_area_area.setText("Limpiar campos");
        bot_limpiarCampos_area_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_limpiarCampos_area_areaActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alojamientos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jButton1.setText("Añadir alojamiento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        campo_alojamientos.setEditable(false);
        campo_alojamientos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        campo_alojamientos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campo_alojamientos))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(campo_alojamientos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout panelAreasLayout = new javax.swing.GroupLayout(panelAreas);
        panelAreas.setLayout(panelAreasLayout);
        panelAreasLayout.setHorizontalGroup(
            panelAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelAreasLayout.createSequentialGroup()
                        .addComponent(lab_nueva_area_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campo_nuevo_parque_area_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAreasLayout.createSequentialGroup()
                        .addComponent(lab_nueva_area_km, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campo_nuevo_parque_area_km))
                    .addGroup(panelAreasLayout.createSequentialGroup()
                        .addComponent(bot_nueva_especie_animal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bot_nueva_especie_vegetal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(panelEspeciesExistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bot_guardarArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot_limpiarCampos_area_area, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panelAreasLayout.setVerticalGroup(
            panelAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreasLayout.createSequentialGroup()
                .addGroup(panelAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEspeciesExistentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelAreasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bot_guardarArea, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bot_limpiarCampos_area_area, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(panelAreasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lab_nueva_area_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_nuevo_parque_area_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_nueva_area_km, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_nuevo_parque_area_km, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bot_nueva_especie_animal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bot_nueva_especie_vegetal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        campo_nuevo_parque_nopmbre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campo_nuevo_parque_nopmbre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campo_nuevo_parque_fecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campo_nuevo_parque_fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campo_nuevo_parque_entradas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        campo_nuevo_parque_entradas.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        combo_ubicacion_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una región", "Atlantico", "Cordoba", "Antioquia", "Guajira", "Bolivar", "Sucre", "Santander", "Norte de Santander" }));
        combo_ubicacion_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_ubicacion_1ActionPerformed(evt);
            }
        });

        combo_ubicacion_2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una región", "Atlantico", "Cordoba", "Antioquia", "Guajira", "Bolivar", "Sucre", "Santander", "Norte de Santander" }));

        combo_ubicacion_3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una región", "Atlantico", "Cordoba", "Antioquia", "Guajira", "Bolivar", "Sucre", "Santander", "Norte de Santander" }));

        combo_ubicacion_4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una región", "Atlantico", "Cordoba", "Antioquia", "Guajira", "Bolivar", "Sucre", "Santander", "Norte de Santander" }));

        panelAreasExistentes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Áreas existentes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        area_areas_existentes.setEditable(false);
        area_areas_existentes.setColumns(20);
        area_areas_existentes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        area_areas_existentes.setRows(5);
        jScrollPane1.setViewportView(area_areas_existentes);

        javax.swing.GroupLayout panelAreasExistentesLayout = new javax.swing.GroupLayout(panelAreasExistentes);
        panelAreasExistentes.setLayout(panelAreasExistentesLayout);
        panelAreasExistentesLayout.setHorizontalGroup(
            panelAreasExistentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreasExistentesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelAreasExistentesLayout.setVerticalGroup(
            panelAreasExistentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAreasExistentesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        bot_limpiar_campos_areas.setText("Limpiar campos");
        bot_limpiar_campos_areas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_limpiar_campos_areasActionPerformed(evt);
            }
        });

        bot_GuardarParque.setText("Guardar Parque");
        bot_GuardarParque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_GuardarParqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNuevoParqueLayout = new javax.swing.GroupLayout(panelNuevoParque);
        panelNuevoParque.setLayout(panelNuevoParqueLayout);
        panelNuevoParqueLayout.setHorizontalGroup(
            panelNuevoParqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevoParqueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNuevoParqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab_descripcion_aniadirparque, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
                    .addComponent(panelAreas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelNuevoParqueLayout.createSequentialGroup()
                        .addGroup(panelNuevoParqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelNuevoParqueLayout.createSequentialGroup()
                                .addComponent(lab_nuevo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campo_nuevo_parque_nopmbre, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNuevoParqueLayout.createSequentialGroup()
                                .addComponent(lab_nuevo_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campo_nuevo_parque_fecha))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNuevoParqueLayout.createSequentialGroup()
                                .addComponent(lab_nuevo_entradas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campo_nuevo_parque_entradas))
                            .addGroup(panelNuevoParqueLayout.createSequentialGroup()
                                .addComponent(lab_nuevo_ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelNuevoParqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(combo_ubicacion_3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combo_ubicacion_1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(panelNuevoParqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combo_ubicacion_4, 0, 140, Short.MAX_VALUE)
                                    .addComponent(combo_ubicacion_2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(125, 125, 125)
                        .addGroup(panelNuevoParqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelAreasExistentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelNuevoParqueLayout.createSequentialGroup()
                                .addComponent(bot_limpiar_campos_areas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bot_GuardarParque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panelNuevoParqueLayout.setVerticalGroup(
            panelNuevoParqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevoParqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lab_descripcion_aniadirparque, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelNuevoParqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNuevoParqueLayout.createSequentialGroup()
                        .addGroup(panelNuevoParqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_nuevo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_nuevo_parque_nopmbre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelNuevoParqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_nuevo_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_nuevo_parque_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelNuevoParqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_nuevo_entradas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_nuevo_parque_entradas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelNuevoParqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lab_nuevo_ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_ubicacion_1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_ubicacion_2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelAreasExistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelNuevoParqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNuevoParqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(combo_ubicacion_3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(combo_ubicacion_4))
                    .addGroup(panelNuevoParqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bot_limpiar_campos_areas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bot_GuardarParque, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAreas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNuevoParque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(panelNuevoParque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelDePestanias.addTab("Añadir PN", jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));

        jLabel1.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        jLabel1.setText("Selecciona de la lista de parque, el que desea gestionar");

        tablaDeParques.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Areas", "Entradas", "Alojamientos", "Fecha de inaguración"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaDeParques);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGestionarParqueLayout = new javax.swing.GroupLayout(panelGestionarParque);
        panelGestionarParque.setLayout(panelGestionarParqueLayout);
        panelGestionarParqueLayout.setHorizontalGroup(
            panelGestionarParqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGestionarParqueLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGestionarParqueLayout.setVerticalGroup(
            panelGestionarParqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelDePestanias.addTab("Gestionar PN", panelGestionarParque);

        javax.swing.GroupLayout panelVisitasLayout = new javax.swing.GroupLayout(panelVisitas);
        panelVisitas.setLayout(panelVisitasLayout);
        panelVisitasLayout.setHorizontalGroup(
            panelVisitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        panelVisitasLayout.setVerticalGroup(
            panelVisitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        panelDePestanias.addTab("Visitas a PN", panelVisitas);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDePestanias)
                .addContainerGap())
            .addComponent(lab_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(lab_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDePestanias)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bot_nueva_especie_animalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_nueva_especie_animalActionPerformed
        new NuevaEspecieAnimal().setVisible(true);
        
    }//GEN-LAST:event_bot_nueva_especie_animalActionPerformed

    private void bot_guardarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_guardarAreaActionPerformed
        String nomb_area = campo_nuevo_parque_area_nombre.getText();
        String km_area = campo_nuevo_parque_area_km.getText();
        
        if(nomb_area.equals("") || km_area.equals("")){
            JOptionPane.showMessageDialog(this, "Por favor completa todos los campos", "Datos imcompletos", JOptionPane.INFORMATION_MESSAGE);
        }else{
            boolean va_bien = true;
            float km = 0;
            try{
                km = Float.parseFloat(km_area);
            }catch(NumberFormatException e){
                va_bien = false;
            }
            if(va_bien){
                JOptionPane.showMessageDialog(this, "El área se guardo correctamente", "Área guardada", JOptionPane.INFORMATION_MESSAGE);
                nuevas_areas.add(new Area(nuevas_especies, nomb_area, km, null));
                area_areas_existentes.setText(area_areas_existentes.getText() + "; " + nomb_area);
                
                //System.out.println("AREAS " + nuevas_areas.size());
                
                bot_limpiarCampos_area_area.doClick();
                
                //System.out.println("AREAS DESPUES " + nuevas_areas.size());
            }
            
            
            
        }
    }//GEN-LAST:event_bot_guardarAreaActionPerformed

    private void bot_limpiarCampos_area_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_limpiarCampos_area_areaActionPerformed
        campo_nuevo_parque_area_km.setText("");
        campo_nuevo_parque_area_nombre.setText("");
        area_especies_existentes.setText("");
        nuevas_especies.clear();
        //nuevas_areas.clear();
    }//GEN-LAST:event_bot_limpiarCampos_area_areaActionPerformed

    private void bot_limpiar_campos_areasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_limpiar_campos_areasActionPerformed
        campo_nuevo_parque_entradas.setText("");
        campo_nuevo_parque_fecha.setText("");
        campo_nuevo_parque_nopmbre.setText("");
        nuevas_areas.clear();
        nuevas_especies.clear();
        nuevos_alojamientos.clear();
        combo_ubicacion_1.setSelectedIndex(0);
        combo_ubicacion_2.setSelectedIndex(0);
        combo_ubicacion_3.setSelectedIndex(0);
        combo_ubicacion_4.setSelectedIndex(0);
        area_areas_existentes.setText("");
        area_especies_existentes.setText("");
        campo_alojamientos.setText("");
    }//GEN-LAST:event_bot_limpiar_campos_areasActionPerformed

    private void bot_GuardarParqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_GuardarParqueActionPerformed
        String nombre_parque = campo_nuevo_parque_nopmbre.getText();
        String entradas_parques = campo_nuevo_parque_entradas.getText();
        String fecha_inagu_parque = campo_nuevo_parque_fecha.getText();
        int ub1 = combo_ubicacion_1.getSelectedIndex();
        int ub2 = combo_ubicacion_2.getSelectedIndex();
        int ub3 = combo_ubicacion_3.getSelectedIndex();
        int ub4 = combo_ubicacion_4.getSelectedIndex();
        
        if((ub1 == 0 && ub2 == 0 && ub3 == 0 && ub4 == 0) || nombre_parque.equals("") || entradas_parques.equals("") || fecha_inagu_parque.equals("") || nuevas_areas.size() == 0){
            JOptionPane.showMessageDialog(this, "Por favor completa todos los campos", "Datos imcompletos", JOptionPane.INFORMATION_MESSAGE);
            
        }else{
            int num_entradas = 0;
            boolean vamos_bien = true;
                
            try{
                num_entradas = Integer.parseInt(entradas_parques);
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "El numero de entradas no es correcto", "Formato incorrecto", JOptionPane.INFORMATION_MESSAGE);
                vamos_bien = false;
            }
            
            //Añadimos las regiones del parque
            ArrayList<Region> regiones_nuevo_parque = new ArrayList<Region>();
            if(ub1 != ub2 && ub1 != ub3 && ub1 != ub4 && ub1 != 0){
                regiones_nuevo_parque.add(regiones.get(ub1 - 1));
            }
            if(ub2 != ub1 && ub2 != ub3 && ub2 != ub4 && ub2 != 0){
                regiones_nuevo_parque.add(regiones.get(ub2 - 1));
            }
            if(ub3 != ub1 && ub3 != ub2 && ub3 != ub4 && ub3 != 0){
                regiones_nuevo_parque.add(regiones.get(ub3 - 1));
            }
            if(ub4 != ub1 && ub4 != ub2 && ub4 != ub3 && ub4 != 0){
                regiones_nuevo_parque.add(regiones.get(ub4 - 1));
            }
            
            System.out.println("AREAS " + nuevas_areas.size());
            
            Parque nuevo_parque = new Parque();
            nuevo_parque.setNombre(nombre_parque);
            nuevo_parque.setNumentrada(num_entradas);
            nuevo_parque.setNumarea(nuevas_areas);
            nuevo_parque.setInaguracion(fecha_inagu_parque);
            nuevo_parque.setUbicaicon(regiones_nuevo_parque);
            nuevo_parque.setAlojamiento(nuevos_alojamientos);
            
            System.out.println("AREAS DESPUES " + nuevas_areas.size());
            
            PARQUES.add(nuevo_parque);
            
            JOptionPane.showMessageDialog(this, "El parque fue añadido correctamente", "Exito al guardar", JOptionPane.INFORMATION_MESSAGE);
            //nuevas_areas.clear();
            bot_limpiarCampos_area_area.doClick();
            bot_limpiar_campos_areas.doClick();
            llenarDatos();
            for(int i = 0; i<PARQUES.size(); i++){
                System.err.println("---" + PARQUES.get(i).getNumarea().size());
            }
        }
        
    }//GEN-LAST:event_bot_GuardarParqueActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new NuevoAlojamiento().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bot_nueva_especie_vegetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot_nueva_especie_vegetalActionPerformed
        new NuevaEspecieVegetal().setVisible(true);
    }//GEN-LAST:event_bot_nueva_especie_vegetalActionPerformed

    private void combo_ubicacion_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_ubicacion_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_ubicacion_1ActionPerformed

   
    
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_areas_existentes;
    private javax.swing.JTextArea area_especies_existentes;
    private javax.swing.JButton bot_GuardarParque;
    private javax.swing.JButton bot_guardarArea;
    private javax.swing.JButton bot_limpiarCampos_area_area;
    private javax.swing.JButton bot_limpiar_campos_areas;
    private javax.swing.JButton bot_nueva_especie_animal;
    private javax.swing.JButton bot_nueva_especie_vegetal;
    private javax.swing.JTextField campo_alojamientos;
    private javax.swing.JTextField campo_nuevo_parque_area_km;
    private javax.swing.JTextField campo_nuevo_parque_area_nombre;
    private javax.swing.JTextField campo_nuevo_parque_entradas;
    private javax.swing.JTextField campo_nuevo_parque_fecha;
    private javax.swing.JTextField campo_nuevo_parque_nopmbre;
    private javax.swing.JComboBox<String> combo_ubicacion_1;
    private javax.swing.JComboBox<String> combo_ubicacion_2;
    private javax.swing.JComboBox<String> combo_ubicacion_3;
    private javax.swing.JComboBox<String> combo_ubicacion_4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lab_descripcion_aniadirparque;
    private javax.swing.JLabel lab_nueva_area_km;
    private javax.swing.JLabel lab_nueva_area_nombre;
    private javax.swing.JLabel lab_nuevo_entradas;
    private javax.swing.JLabel lab_nuevo_fecha;
    private javax.swing.JLabel lab_nuevo_nombre;
    private javax.swing.JLabel lab_nuevo_ubicacion;
    private javax.swing.JLabel lab_titulo;
    private javax.swing.JPanel panelAreas;
    private javax.swing.JPanel panelAreasExistentes;
    private javax.swing.JTabbedPane panelDePestanias;
    private javax.swing.JPanel panelEspeciesExistentes;
    private javax.swing.JPanel panelGestionarParque;
    private javax.swing.JPanel panelNuevoParque;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelVisitas;
    private javax.swing.JTable tablaDeParques;
    // End of variables declaration//GEN-END:variables

    public void llenarDatos(){
        regiones.clear();
        regiones.add(new Region("Cordoba", "JAV"));
        regiones.add(new Region("Atlantico", "Comision reguladora de Parques naturales de Atlantico"));
        regiones.add(new Region("Cordoba", "EPO"));
        regiones.add(new Region("Antioquia", "MedaAmbiente"));
        regiones.add(new Region("Guajira", "MCA"));
        regiones.add(new Region("Bolivar", "EPA"));
        regiones.add(new Region("Sucre", "APA"));
        regiones.add(new Region("Santander", "CRPNS"));
        regiones.add(new Region("Norte de Santander", "PNS"));
        
        int contador_fila = 0;
        for(int i = 0; i < PARQUES.size(); i++){
            tablaDeParques.setValueAt(PARQUES.get(i).getNombre(), contador_fila, 0);
            tablaDeParques.setValueAt(PARQUES.get(i).getNumarea().size(), contador_fila, 1);
            tablaDeParques.setValueAt(PARQUES.get(i).getNumentrada(), contador_fila, 2);
            tablaDeParques.setValueAt(PARQUES.get(i).getNumalojamiento().size(), contador_fila, 3);
            tablaDeParques.setValueAt(PARQUES.get(i).getInaguracion(), contador_fila, 4);
            contador_fila++;
            
            
        }
    }

    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * CLASE DE AÑADIR ESPECIE ANIMAL, LA PUEDES AÑADIR EN LA OTRA CLASE CON EL MISMO NOMBRE Y DESPES REEMPLAZAS ESTA CON TODO EL CODIGO DE LA OTRA
     */
    
    
public class NuevaEspecieAnimal extends javax.swing.JFrame {

    /**
     * Creates new form NuevaEspecieAnimal
     */
    
    private Animal nuevaEspecie = new Animal();
    
    public NuevaEspecieAnimal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lab_titulo = new javax.swing.JLabel();
        lab_nombre_cientifico = new javax.swing.JLabel();
        lab_nombre = new javax.swing.JLabel();
        lab_numero_especies = new javax.swing.JLabel();
        lab_periodo_celo = new javax.swing.JLabel();
        lab_alimentos = new javax.swing.JLabel();
        campo_nombre_cient = new javax.swing.JTextField();
        campo_nombre_comun = new javax.swing.JTextField();
        campo_numero_esp = new javax.swing.JTextField();
        campo_periodo_celo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        campo_alimentos = new javax.swing.JTextArea();
        bor_guardarEspecie = new javax.swing.JButton();
        bot_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lab_titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lab_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_titulo.setText("Añadir especie animal");

        lab_nombre_cientifico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab_nombre_cientifico.setText("Nombre cientifico:");

        lab_nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab_nombre.setText("Nombre común:");

        lab_numero_especies.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab_numero_especies.setText("Numero de especies:");

        lab_periodo_celo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab_periodo_celo.setText("Periodo de celo:");

        lab_alimentos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab_alimentos.setText("Alimentos:");

        campo_nombre_cient.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campo_nombre_comun.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campo_numero_esp.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campo_periodo_celo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campo_periodo_celo.setToolTipText("En formato (DD-MM-AAAA)");

        campo_alimentos.setColumns(20);
        campo_alimentos.setRows(5);
        jScrollPane1.setViewportView(campo_alimentos);

        bor_guardarEspecie.setText("Guardar Especie");
        bor_guardarEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bor_guardarEspecieActionPerformed(evt);
            }
        });

        bot_cancelar.setText("Cancelar");
        
        bot_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lab_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lab_nombre_cientifico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campo_nombre_cient))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lab_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campo_nombre_comun))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lab_numero_especies, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campo_numero_esp))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lab_periodo_celo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campo_periodo_celo))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lab_alimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(bor_guardarEspecie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bot_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(lab_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_nombre_cientifico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_nombre_cient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_nombre_comun, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_numero_especies, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_numero_esp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_periodo_celo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_periodo_celo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab_alimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bor_guardarEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bot_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void bor_guardarEspecieActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        String nom_cie = campo_nombre_cient.getText();
        String nom_com = campo_nombre_comun.getText();
        String num_esp = campo_numero_esp.getText();
        String fec_cel = campo_periodo_celo.getText();
        String aliment = campo_alimentos.getText();
        
        if(nom_com.equals("") || nom_cie.equals("") || num_esp.equals("") || fec_cel.equals("") || aliment.equals("")){
            JOptionPane.showMessageDialog(this, "Por favor completa todos los campos", "Datos imcompletos", JOptionPane.INFORMATION_MESSAGE);
            
        }else{
            boolean guardado_correcto = true;
            ///JOptionPane.showMessageDialog(this, "La nueva especie fue almacenada correctamente en el area", "Especie almacenada", JOptionPane.INFORMATION_MESSAGE);
            int num_especies = 0;
            try{
                
                num_especies = Integer.parseInt(num_esp);
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "El numero de especies no es correcto", "Formato incorrecto", JOptionPane.INFORMATION_MESSAGE);
                guardado_correcto = false;
            }
            
            //VALIDAR FECHA AQUI
            /*if(guardado_correcto){
                String[] fecha_pre = fec_cel.split("-");
                fec_cel.
            }*/
            if(guardado_correcto){
                nuevaEspecie.setAlimento(aliment);
                nuevaEspecie.setNomcin(nom_cie);
                nuevaEspecie.setNomvul(nom_com);
                nuevaEspecie.setNum(num_especies);
                nuevaEspecie.setPericelo(fec_cel);
                
                JOptionPane.showMessageDialog(this, "La nueva especie fue almacenada correctamente en el area", "Especie almacenada", JOptionPane.INFORMATION_MESSAGE);
                
                nuevas_especies.add(nuevaEspecie);
                area_especies_existentes.setText(area_especies_existentes.getText() + "; " + nuevaEspecie.getNomvul());
                this.dispose();
            }
                    
            
            
            
            
        }
    }            
    
    private void bot_cancelarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        this.dispose();
    }     

    // Variables declaration - do not modify                     
    private javax.swing.JButton bor_guardarEspecie;
    private javax.swing.JButton bot_cancelar;
    private javax.swing.JTextArea campo_alimentos;
    private javax.swing.JTextField campo_nombre_cient;
    private javax.swing.JTextField campo_nombre_comun;
    private javax.swing.JTextField campo_numero_esp;
    private javax.swing.JTextField campo_periodo_celo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lab_alimentos;
    private javax.swing.JLabel lab_nombre;
    private javax.swing.JLabel lab_nombre_cientifico;
    private javax.swing.JLabel lab_numero_especies;
    private javax.swing.JLabel lab_periodo_celo;
    private javax.swing.JLabel lab_titulo;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration                   
}





















public class NuevaEspecieVegetal extends javax.swing.JFrame {

    /**
     * Creates new form NuevaEspecieAnimal
     */
    
    private Vegetal nuevaEspecie = new Vegetal();
    
    public NuevaEspecieVegetal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lab_titulo = new javax.swing.JLabel();
        lab_nombre_cientifico = new javax.swing.JLabel();
        lab_nombre = new javax.swing.JLabel();
        lab_numero_especies = new javax.swing.JLabel();
        campo_nombre_cient = new javax.swing.JTextField();
        campo_nombre_comun = new javax.swing.JTextField();
        campo_perido_flora = new javax.swing.JTextField();
        bor_guardarEspecie = new javax.swing.JButton();
        bot_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lab_titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lab_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_titulo.setText("Añadir especie vegetal");

        lab_nombre_cientifico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab_nombre_cientifico.setText("Nombre cientifico:");

        lab_nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab_nombre.setText("Nombre común:");

        lab_numero_especies.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab_numero_especies.setText("Periodo de floración");

        campo_nombre_cient.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campo_nombre_comun.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campo_perido_flora.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        bor_guardarEspecie.setText("Guardar Especie");
        bor_guardarEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bor_guardarEspecieActionPerformed(evt);
            }
        });

        bot_cancelar.setText("Cancelar");
        bot_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lab_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lab_nombre_cientifico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campo_nombre_cient, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lab_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campo_nombre_comun))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lab_numero_especies, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campo_perido_flora)))
                .addContainerGap())
            .addComponent(bor_guardarEspecie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bot_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(lab_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_nombre_cientifico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_nombre_cient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_nombre_comun, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_numero_especies, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_perido_flora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(bor_guardarEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bot_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void bor_guardarEspecieActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        String nom_cie = campo_nombre_cient.getText();
        String nom_com = campo_nombre_comun.getText();
        String per_flo = campo_perido_flora.getText();
        
        if(nom_com.equals("") || nom_cie.equals("")){
            JOptionPane.showMessageDialog(this, "Por favor completa todos los campos", "Datos imcompletos", JOptionPane.INFORMATION_MESSAGE);
            
        }else{
                if(per_flo.equals("")){
                    nuevaEspecie.setFloracion(false);
                }else{
                    nuevaEspecie.setFloracion(true);
                    nuevaEspecie.setPer_floracion(per_flo);
                }
                
                
                nuevaEspecie.setNomcin(nom_cie);
                nuevaEspecie.setNomvul(nom_com);
                
                JOptionPane.showMessageDialog(this, "La nueva especie fue almacenada correctamente en el area", "Especie almacenada", JOptionPane.INFORMATION_MESSAGE);

                nuevas_especies.add(nuevaEspecie);
                area_especies_existentes.setText(area_especies_existentes.getText() + "; " + nuevaEspecie.getNomvul());
                this.dispose();
        }
    }                                                  

    private void bot_cancelarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        this.dispose();
    }                                            

    // Variables declaration - do not modify                     
    private javax.swing.JButton bor_guardarEspecie;
    private javax.swing.JButton bot_cancelar;
    private javax.swing.JTextField campo_nombre_cient;
    private javax.swing.JTextField campo_nombre_comun;
    private javax.swing.JTextField campo_perido_flora;
    private javax.swing.JLabel lab_nombre;
    private javax.swing.JLabel lab_nombre_cientifico;
    private javax.swing.JLabel lab_numero_especies;
    private javax.swing.JLabel lab_titulo;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration                   
}










































public class NuevoAlojamiento extends javax.swing.JFrame {

    /**
     * Creates new form NuevaEspecieAnimal
     */
    
    private Alojamiento nuevaAlojamiento = new Alojamiento();
    
    public NuevoAlojamiento() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lab_titulo = new javax.swing.JLabel();
        lab_nombre_cientifico = new javax.swing.JLabel();
        lab_nombre = new javax.swing.JLabel();
        lab_numero_especies = new javax.swing.JLabel();
        lab_periodo_celo = new javax.swing.JLabel();
        campo_nombre = new javax.swing.JTextField();
        campo_capacidad = new javax.swing.JTextField();
        campo_valor = new javax.swing.JTextField();
        campo_categoria = new javax.swing.JTextField();
        bor_guardarEspecie = new javax.swing.JButton();
        bot_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lab_titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lab_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab_titulo.setText("Añadir nuevo alojamiento");

        lab_nombre_cientifico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab_nombre_cientifico.setText("Nombre:");

        lab_nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab_nombre.setText("Capacidad");

        lab_numero_especies.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab_numero_especies.setText("Valor:");

        lab_periodo_celo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab_periodo_celo.setText("Categoria");

        campo_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campo_capacidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campo_valor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        campo_categoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campo_categoria.setToolTipText("En formato (DD-MM-AAAA)");

        bor_guardarEspecie.setText("Guardar Alojamiento");
        bor_guardarEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bor_guardarEspecieActionPerformed(evt);
            }
        });

        bot_cancelar.setText("Cancelar");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lab_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lab_nombre_cientifico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campo_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lab_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campo_capacidad))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lab_numero_especies, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campo_valor))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lab_periodo_celo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campo_categoria)))
                .addContainerGap())
            .addComponent(bor_guardarEspecie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bot_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(lab_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_nombre_cientifico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_numero_especies, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_periodo_celo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bor_guardarEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bot_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void bor_guardarEspecieActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        String nom_aloj = campo_nombre.getText();
        String cap_aloj = campo_capacidad.getText();
        String val_aloj = campo_valor.getText();
        String cat_aloj = campo_categoria.getText();
        
        if(nom_aloj.equals("") || cap_aloj.equals("") || val_aloj.equals("") || cat_aloj.equals("")){
            JOptionPane.showMessageDialog(this, "Por favor completa todos los campos", "Datos imcompletos", JOptionPane.INFORMATION_MESSAGE);
            
        }else{
            boolean guardado_correcto = true;
            ///JOptionPane.showMessageDialog(this, "La nueva especie fue almacenada correctamente en el area", "Especie almacenada", JOptionPane.INFORMATION_MESSAGE);
            int num_capacidad = 0;
            try{
                
                num_capacidad = Integer.parseInt(cap_aloj);
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "El numero de la capacidad no es correcto", "Formato incorrecto", JOptionPane.INFORMATION_MESSAGE);
                guardado_correcto = false;
            }
            
            //VALIDAR FECHA AQUI
            /*if(guardado_correcto){
                String[] fecha_pre = fec_cel.split("-");
                fec_cel.
            }*/
            if(guardado_correcto){
                nuevaAlojamiento.setCapacidad(num_capacidad);
                nuevaAlojamiento.setNombre(nom_aloj);
                nuevaAlojamiento.setValor(val_aloj);
                nuevaAlojamiento.setCategoria(cat_aloj);
                
                
                JOptionPane.showMessageDialog(this, "La nueva especie fue almacenada correctamente en el area", "Especie almacenada", JOptionPane.INFORMATION_MESSAGE);
                //JOptionPane.showMessageDialog(this, "La nueva especie fue almacenada correctamente en el area", "Especie almacenada", JOptionPane.INFORMATION_MESSAGE);
                
                nuevos_alojamientos.add(nuevaAlojamiento);
                campo_alojamientos.setText(campo_alojamientos.getText() + "; " + nuevaAlojamiento.getNombre());
                this.dispose();
            }
                    
            
            
            
            
        }
    }                                                  

    // Variables declaration - do not modify                     
    private javax.swing.JButton bor_guardarEspecie;
    private javax.swing.JButton bot_cancelar;
    private javax.swing.JTextField campo_capacidad;
    private javax.swing.JTextField campo_categoria;
    private javax.swing.JTextField campo_nombre;
    private javax.swing.JTextField campo_valor;
    private javax.swing.JLabel lab_nombre;
    private javax.swing.JLabel lab_nombre_cientifico;
    private javax.swing.JLabel lab_numero_especies;
    private javax.swing.JLabel lab_periodo_celo;
    private javax.swing.JLabel lab_titulo;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration                   
}










}
